name:                dw-webhooks
version:             0.1.0.0
github:              srdqty/dw-webhooks
license:             BSD3
author:              Sofia Donataccio
maintainer:          srdqty@gmail.com
copyright:           Copyright (c) 2018 Sofia Donataccio

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:
# description:
# category:            Web

dependencies:
  - base >= 4.7 && < 5
  - libjenkins >= 0.8.4 && < 0.9
  - dhall >= 1.14.0 && < 1.15
  - text >= 1.2.3.0 && < 1.3
  - aeson >= 1.2.4.0 && < 1.3

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  dw-webhooks:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - dw-webhooks

tests:
  dw-webhooks-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - dw-webhooks
      - hspec
