name:                dw-webhooks
version:             0.1.0.0
github:              srdqty/dw-webhooks
license:             BSD3
author:              Sofia Donataccio
maintainer:          srdqty@gmail.com
copyright:           Copyright (c) 2018 Sofia Donataccio

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:
# description:
# category:            Web

dependencies:
  - aeson >= 1.2.4.0 && < 1.3
  - base >= 4.7 && < 5
  - bytestring >= 0.10.8.2 && < 0.11
  - cryptonite == 0.25
  - dhall >= 1.14.0 && < 1.15
  - http-types >= 0.12.1 && < 0.13
  - libjenkins >= 0.8.4 && < 0.9
  - memory == 0.14.16
  - text >= 1.2.3.0 && < 1.3
  - yesod-core >= 1.4.37.3 && < 1.5
  - wai >= 3.2.1.2 && < 3.3
  - warp >= 3.2.22 && < 3.3

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  dw-webhooks:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - dw-webhooks

tests:
  dw-webhooks-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - dw-webhooks
      - hspec
      - hspec-discover
